export declare const fufelLib: {
    concat: (...es: any[]) => any;
    concatWithSeparator: (sep?: string, ...es: any[]) => string;
    ilike: (str: string, pattern?: string) => boolean;
    like: (str: string, pattern?: string) => boolean;
    initcap: (str: string) => string;
    left: (str: string, count?: number) => string;
    right: (str: string, count?: number) => string;
    substring: (str: string, offset: number, len?: number) => string;
    abs: (num: number) => number;
    power: (num: number, exp: number) => number;
    sqrt: (num: number) => number;
    ceil: (num: number) => number;
    floor: (num: number) => number;
    round: (num: number) => number;
    sin: (angle: number) => number;
    cos: (angle: number) => number;
    tan: (angle: number) => number;
    radians: (degrees: number) => number;
    pi: () => Math["PI"];
    get_tag: (e: import('../defs/bi').ILocation | import('../defs/bi').IPeriod | import('../defs/common').IMetric, tagAxis: string) => any;
    with_tag: (es: import('../defs/common').ITaggedEntity[], tagId: string) => import('../defs/common').ITaggedEntity[];
    one_with_tag: (es: import('../defs/common').ITaggedEntity[], tagId: string) => import('../defs/common').ITaggedEntity;
    pick_with_tags: (es: import('../defs/common').ITaggedEntity[], ...tagIds: string[]) => import('../defs/common').ITaggedEntity[];
    me_or_ancestors: (es: import('../defs/common').IEntity[], state?: import('../defs/common').IEntity[], arr?: any, defaultArr?: any) => import('../defs/common').IEntity[];
    children: (es: import('../defs/common').IEntity[]) => import('../defs/common').IEntity[];
    parents: (es: import('../defs/common').IEntity[]) => import('../defs/common').IEntity[];
    paths: (es: import('../defs/common').IEntity[]) => import('../defs/common').IEntity[];
    me_and_paths: (es: import('../defs/common').IEntity[]) => unknown[];
    siblings: (es: import('../defs/common').IEntity[]) => import('../defs/common').IEntity[];
    descendants: (es: import('../defs/common').IEntity[]) => import('../defs/common').IEntity[];
    me_and_descendants: (es: import('../defs/common').IEntity[]) => import('../defs/common').IEntity[];
    avg: (vec: number[]) => number;
    createConstMatrix: typeof import('../utils').createConstMatrix;
    createConstVector: typeof import('../utils').createConstVector;
    matrixSum: typeof import('../utils').matrixSum;
    vectorSum: typeof import('../utils').vectorSum;
    dplus: typeof any;
    'sf:lpe': (ast: any, ctx: any, rs: any) => any;
    'sf:when': (ast: any, ctx: any, rs: any) => any;
    last: <T>(es: T[], dateInterval: number) => T | T[];
    exclude: <T>(a: T[], b: T) => T[];
    indexOf: <T>(source: T[] | string, searchElement: T, fromIndex?: number) => number;
    join: <T>(array: T[], separator: string) => string;
    includes: <T>(source: T[] | string, needle: any, fromIndex?: number) => boolean;
    slice: <T>(source: T[] | string, start?: number, end?: number) => T[] | string;
    split: (source: any, separator: string | RegExp, limit?: number) => string[];
    reverse: <T extends string | any[]>(source: T) => T;
    replace: (source: string, replaceStringOrRegExp: string | RegExp, newStr?: string) => string;
    replaceAll: (source: string, replaceStringOrRegExp: string | RegExp, newStr?: string) => string;
    match: (source: string, pattern: string | RegExp) => RegExpMatchArray | null;
    matchAll: (source: string, pattern: RegExp) => IterableIterator<RegExpMatchArray>;
    substr: (str: string, from: number, to: number) => string;
    startsWith: (str: string, template: string) => boolean;
    padStart: (source: unknown, targetLength: number, padString?: string) => string;
    padEnd: (source: unknown, targetLength: number, padString?: string) => string;
    rgba: (r: number, g: number, b: number, a?: number) => string;
    hsl: (hue: number, saturation: number, luminosity: number) => string;
    log: (expression: any) => any;
    print: (...args: any[]) => void;
    hash: (...args: any[]) => any;
    now: () => string;
    between: <T>(from: T, to: T) => T[];
    format: typeof any;
    'sf:filterIt': (ast: any, ctx: any, rs: any) => any;
    'sf:mapIt': (ast: any, ctx: any, rs: any) => any;
    'sf:switch': (ast: any, ctx: any, rs: any) => any;
    'sf:cond': (ast: any, ctx: any, rs: any) => any;
    'sf:groupAB': (ast: any, ctx: any, rs: any) => any[];
};
export declare function lpeRun(lpeCode: any, ctx: any, opts?: any): any;
export default lpeRun;
