interface IconColoredCheckboxProps {
    className?: string;
    value?: boolean;
    color?: string;
    bgColor?: string;
    style?: any;
    onPress?: () => any;
}
export declare const IconColoredCheckbox: ({ className, value, color, bgColor, style, onPress }: IconColoredCheckboxProps) => JSX.Element;
export declare const IconWorkBench: () => JSX.Element;
export declare const IconRect: () => JSX.Element;
export declare const IconUser: () => JSX.Element;
export declare const IconUserM: () => JSX.Element;
export declare const IconTree: () => JSX.Element;
export declare const IconList: () => JSX.Element;
export declare const IconCube: () => JSX.Element;
export declare const IconLogo: () => JSX.Element;
export declare const IconLeftChevron: () => JSX.Element;
export declare const IconRightChevron: () => JSX.Element;
export declare const IconRhombus: () => JSX.Element;
export declare const IconHelp: () => JSX.Element;
export declare const IconSets: () => JSX.Element;
export declare const IconSearch: () => JSX.Element;
export declare const IconDropdown: () => JSX.Element;
export declare const IconDownChevron: () => JSX.Element;
export declare const IconEye: () => JSX.Element;
export declare const IconEyeClosed: () => JSX.Element;
export declare const IconWarning: () => JSX.Element;
export declare const IconLock: () => JSX.Element;
export declare const IconLuxmsBI: () => JSX.Element;
export declare const IconSms: () => JSX.Element;
export declare const IconCancel: () => JSX.Element;
export declare const IconSetting: () => JSX.Element;
export declare const IconNoIcon: () => JSX.Element;
export declare const IconDefaultMenu: () => JSX.Element;
export {};
