import React from 'react';
import { BIIcon } from './ui/BIIcon';
import { VizelFromCfg } from './ui/VizelFromCfg';
import { WpLoadingIcon } from './ui/WpLoadingIcon';
import { DlgShareWithUser } from './ui/DlgShareWithUser';
import AlertsVC, { AlertsVC as AlertsVCNamed } from './ui/AlertsVC';
import { EditMenuItem } from './ui/EditMenuItem';
import { ModalContainer, modalContainer } from './ui/modal-container';
import openModal, { openModal as openModalNamed } from './ui/OpenModalVC';
import VirtualList, { VirtualList as VirtualListNamed } from './ui/VirtualList';
import { DrilldownMenu } from './ui/DrilldownMenu';
import IfICan, { IfICan as IfICanNamed } from './ui/IfICan';
import Search, { Search as SearchNamed } from './ui/Search';
import { OnlyWhenVisible } from './ui/OnlyWhenVisible';
import { ConfirmWindow } from './ui/ConfirmWindow';
import { L10n } from './ui/L10n';
import { LPEEvaluator } from './services/LpeEvaluatorService';

type Component = React.ComponentType<any>;

export { BIIcon };
export { VizelFromCfg };
export { WpLoadingIcon };
export { DlgShareWithUser };
export { AlertsVCNamed as AlertsVC };
export { EditMenuItem };
export { ModalContainer, modalContainer };
export { openModalNamed as openModal };
export { VirtualListNamed as VirtualList };
export { DrilldownMenu };
export { IfICanNamed as IfICan };
export { SearchNamed as Search };
export { OnlyWhenVisible };
export { ConfirmWindow };
export { L10n };
export { LPEEvaluator };

export declare const ContextMenu: Component;
export declare const MainToolbarVC: any;
export declare const MainToolbar: Component;
export declare const MainToolbar__EditModeButton: Component;
export declare const HrefButton: Component;
export declare const MainToolbar__DataBoringButton: Component;
export declare const MainToolbar__ThemeSwitchButton: Component;
export declare const ActionList: Component;
export declare const DlgAbout: Component;
export declare const Profile: Component;
export declare const OptionsProvider: any;
export declare const EditModeVC: any;
export declare const SVGIcon: Component;
export declare const SimpleTable: Component;
export declare const BaseVizelEcharts: any;
export declare const EPlot: any;
export declare const EditModeEnabler: Component;
export declare const L10nVC: any;
export declare const AppPane: Component & Record<string, any>;
export declare const Menu: any;
export declare const MenuState: any;
export declare const JsonSchemaForm: Component;
export declare const VizelYVC: any;
export declare const VizelXVC: any;
export declare const VizelXYVC: any;
export declare const VizelGaugeVC: any;
export declare const VizelPivotMLP: any;
export declare const BaseVizelVC: any;
export declare const VizelKoobControl: Component;
export declare const SelectSortBy: Component;
export declare const RootLogo: Component;
export declare const DsShellHeader: Component;
export declare const Select: Component;
export declare const FileManager: Component;
export declare const ResourcesFilePicker: Component;
export declare const lpeForReact: any;
export declare const lpeCommonContext: any;
export declare const createAtlasLpeForReact: any;
export declare const TitleForVizel: Component;
export declare const SortableTiles: Component;
export declare const VIZEL_TYPES: any;

declare const AvatarIcons: Record<string, Component>;

/**
 * Runtime namespace object exported by `bi-internal/ui`.
 */
declare const _default: {
    IfICan: typeof IfICan;
    VizelFromCfg: typeof VizelFromCfg;
    BIIcon: typeof BIIcon;
    WpLoadingIcon: typeof WpLoadingIcon;
    DlgShareWithUser: typeof DlgShareWithUser;
    ModalContainer: typeof ModalContainer;
    modalContainer: typeof modalContainer;
    AlertsVC: typeof AlertsVC;
    EditMenuItem: typeof EditMenuItem;
    openModal: typeof openModal;
    VirtualList: typeof VirtualList;
    DrilldownMenu: typeof DrilldownMenu;
    ContextMenu: typeof ContextMenu;
    MainToolbarVC: typeof MainToolbarVC;
    MainToolbar: typeof MainToolbar;
    MainToolbar__EditModeButton: typeof MainToolbar__EditModeButton;
    HrefButton: typeof HrefButton;
    MainToolbar__DataBoringButton: typeof MainToolbar__DataBoringButton;
    MainToolbar__ThemeSwitchButton: typeof MainToolbar__ThemeSwitchButton;
    ActionList: typeof ActionList;
    DlgAbout: typeof DlgAbout;
    Profile: typeof Profile;
    OptionsProvider: typeof OptionsProvider;
    EditModeVC: typeof EditModeVC;
    SVGIcon: typeof SVGIcon;
    SimpleTable: typeof SimpleTable;
    BaseVizelEcharts: typeof BaseVizelEcharts;
    EPlot: typeof EPlot;
    EditModeEnabler: typeof EditModeEnabler;
    L10n: typeof L10n;
    L10nVC: typeof L10nVC;
    AppPane: typeof AppPane;
    Menu: typeof Menu;
    MenuState: typeof MenuState;
    JsonSchemaForm: typeof JsonSchemaForm;
    VizelYVC: typeof VizelYVC;
    VizelXVC: typeof VizelXVC;
    VizelXYVC: typeof VizelXYVC;
    VizelGaugeVC: typeof VizelGaugeVC;
    VizelPivotMLP: typeof VizelPivotMLP;
    BaseVizelVC: typeof BaseVizelVC;
    VizelKoobControl: typeof VizelKoobControl;
    Search: typeof Search;
    SelectSortBy: typeof SelectSortBy;
    OnlyWhenVisible: typeof OnlyWhenVisible;
    ConfirmWindow: typeof ConfirmWindow;
    RootLogo: typeof RootLogo;
    DsShellHeader: typeof DsShellHeader;
    Select: typeof Select;
    FileManager: typeof FileManager;
    ResourcesFilePicker: typeof ResourcesFilePicker;
    lpeForReact: typeof lpeForReact;
    lpeCommonContext: typeof lpeCommonContext;
    createAtlasLpeForReact: typeof createAtlasLpeForReact;
    TitleForVizel: typeof TitleForVizel;
    SortableTiles: typeof SortableTiles;
    LPEEvaluator: typeof LPEEvaluator;
    VIZEL_TYPES: typeof VIZEL_TYPES;
    AvatarIcons: typeof AvatarIcons;
};

export default _default;
